version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: eam-mysql-container
    restart: always
    env_file:
      - .env.db
    environment:
      - MYSQL_DATABASE=eam-db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:${DB_PORT}"
